steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/xcraper-backend', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xcraper-backend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'xcraper-backend'
      - '--image=gcr.io/$PROJECT_ID/xcraper-backend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--concurrency=1'
      - '--timeout=3600'
      - '--no-cpu-throttling'
      - '--vpc-connector=desgrabador-postgre'
      - '--vpc-egress=private-ranges-only'
      - >-
        --set-env-vars=DJANGO_SETTINGS_MODULE=config.settings.production,
        DB_NAME=xcraper,DB_USER=xcraper,DB_HOST=10.36.194.4,DB_PORT=5432,
        CORS_ALLOWED_ORIGINS=https://xcraper.chequeabot.com
      - --set-secrets=DB_PASSWORD=xcraper-db-password:latest
      - '--service-account=xcraper-backend@chequeado-249220.iam.gserviceaccount.com'

timeout: 1200s
