version: '3.8'

services:
  backend-test:
    build: ./backend
    ports:
      - "6060:6060"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - SECRET_KEY=test-secret-key-for-local-testing
      - DEBUG=True
      - DB_NAME=test_db
      - DB_USER=test_user
      - DB_PASSWORD=test_pass
      - DB_HOST=db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:6060

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: