version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "6060:6060"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development

  frontend:
    build: ./frontend
    ports:
      - "6070:6070"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend