# Generated by Django 5.0.1 on 2025-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xaccount',
            options={'ordering': ['username'], 'verbose_name': 'Cuenta X', 'verbose_name_plural': 'Cuentas X'},
        ),
        migrations.AlterField(
            model_name='xaccount',
            name='username',
            field=models.CharField(help_text='Sin @, ej: nombreDeUsuario', max_length=100, unique=True),
        ),
    ]
